version: '3.8'
services:
  cartracking-frontend:
    container_name: cartracking-frontend
    restart: unless-stopped
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    volumes:
      - './../:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
